# Generated by Django 5.2.7 on 2025-10-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credentialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pno', models.IntegerField()),
                ('dob', models.DateField()),
                ('password', models.CharField()),
                ('confirm_password', models.CharField(max_length=30)),
            ],
        ),
    ]
